/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MethodRouteImport } from './routes/method'
import { Route as ProductRouteImport } from './routes/product'
import { Route as WorkbenchRouteImport } from './routes/workbench'
import { Route as WorkbenchIndexRouteImport } from './routes/workbench/index'
import { Route as WorkbenchRegwatchRouteImport } from './routes/workbench/regwatch'
import { Route as WorkbenchCasesCaseIdRouteImport } from './routes/workbench/cases.$caseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodRoute = MethodRouteImport.update({
  id: '/method',
  path: '/method',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkbenchRoute = WorkbenchRouteImport.update({
  id: '/workbench',
  path: '/workbench',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkbenchIndexRoute = WorkbenchIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkbenchRoute,
} as any)
const WorkbenchRegwatchRoute = WorkbenchRegwatchRouteImport.update({
  id: '/regwatch',
  path: '/regwatch',
  getParentRoute: () => WorkbenchRoute,
} as any)
const WorkbenchCasesCaseIdRoute = WorkbenchCasesCaseIdRouteImport.update({
  id: '/cases/$caseId',
  path: '/cases/$caseId',
  getParentRoute: () => WorkbenchRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/method': typeof MethodRoute
  '/product': typeof ProductRoute
  '/workbench': typeof WorkbenchRouteWithChildren
  '/workbench/regwatch': typeof WorkbenchRegwatchRoute
  '/workbench/': typeof WorkbenchIndexRoute
  '/workbench/cases/$caseId': typeof WorkbenchCasesCaseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/method': typeof MethodRoute
  '/product': typeof ProductRoute
  '/workbench/regwatch': typeof WorkbenchRegwatchRoute
  '/workbench': typeof WorkbenchIndexRoute
  '/workbench/cases/$caseId': typeof WorkbenchCasesCaseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/method': typeof MethodRoute
  '/product': typeof ProductRoute
  '/workbench': typeof WorkbenchRouteWithChildren
  '/workbench/regwatch': typeof WorkbenchRegwatchRoute
  '/workbench/': typeof WorkbenchIndexRoute
  '/workbench/cases/$caseId': typeof WorkbenchCasesCaseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/method'
    | '/product'
    | '/workbench'
    | '/workbench/regwatch'
    | '/workbench/'
    | '/workbench/cases/$caseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/method'
    | '/product'
    | '/workbench/regwatch'
    | '/workbench'
    | '/workbench/cases/$caseId'
  id:
    | '__root__'
    | '/'
    | '/method'
    | '/product'
    | '/workbench'
    | '/workbench/regwatch'
    | '/workbench/'
    | '/workbench/cases/$caseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MethodRoute: typeof MethodRoute
  ProductRoute: typeof ProductRoute
  WorkbenchRoute: typeof WorkbenchRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/method': {
      id: '/method'
      path: '/method'
      fullPath: '/method'
      preLoaderRoute: typeof MethodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workbench': {
      id: '/workbench'
      path: '/workbench'
      fullPath: '/workbench'
      preLoaderRoute: typeof WorkbenchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workbench/': {
      id: '/workbench/'
      path: '/'
      fullPath: '/workbench/'
      preLoaderRoute: typeof WorkbenchIndexRouteImport
      parentRoute: typeof WorkbenchRoute
    }
    '/workbench/regwatch': {
      id: '/workbench/regwatch'
      path: '/regwatch'
      fullPath: '/workbench/regwatch'
      preLoaderRoute: typeof WorkbenchRegwatchRouteImport
      parentRoute: typeof WorkbenchRoute
    }
    '/workbench/cases/$caseId': {
      id: '/workbench/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/workbench/cases/$caseId'
      preLoaderRoute: typeof WorkbenchCasesCaseIdRouteImport
      parentRoute: typeof WorkbenchRoute
    }
  }
}

interface WorkbenchRouteChildren {
  WorkbenchRegwatchRoute: typeof WorkbenchRegwatchRoute
  WorkbenchIndexRoute: typeof WorkbenchIndexRoute
  WorkbenchCasesCaseIdRoute: typeof WorkbenchCasesCaseIdRoute
}

const WorkbenchRouteChildren: WorkbenchRouteChildren = {
  WorkbenchRegwatchRoute: WorkbenchRegwatchRoute,
  WorkbenchIndexRoute: WorkbenchIndexRoute,
  WorkbenchCasesCaseIdRoute: WorkbenchCasesCaseIdRoute,
}

const WorkbenchRouteWithChildren = WorkbenchRoute._addFileChildren(
  WorkbenchRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MethodRoute: MethodRoute,
  ProductRoute: ProductRoute,
  WorkbenchRoute: WorkbenchRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
