"""Canonical TradePulse shared enums.

Source of truth for all apps. Do not redeclare these literals elsewhere.
"""

from __future__ import annotations

from enum import Enum


class TradeProfile(str, Enum):
    """Application-led transaction profiles (Scrutiny → Maker → Checker)."""

    PRE_SHIPMENT_TRADE_FINANCE = "PRE_SHIPMENT_TRADE_FINANCE"
    LC_ISSUANCE_AMENDMENT = "LC_ISSUANCE_AMENDMENT"
    POST_SHIPMENT_LC_PRESENTATION = "POST_SHIPMENT_LC_PRESENTATION"
    DOCUMENTARY_COLLECTION = "DOCUMENTARY_COLLECTION"
    TRADE_CREDIT_FACTORING = "TRADE_CREDIT_FACTORING"
    TRADE_HOUSE_COMPLIANCE_REVIEW = "TRADE_HOUSE_COMPLIANCE_REVIEW"


class ShipmentMode(str, Enum):
    """Transport mode. AWB ≠ BoL — distinct DocumentTypes."""

    OCEAN = "OCEAN"
    AIR = "AIR"
    MULTIMODAL = "MULTIMODAL"
    UNKNOWN = "UNKNOWN"


class TransactionStage(str, Enum):
    BEFORE_SHIPMENT = "BEFORE_SHIPMENT"
    AFTER_SHIPMENT_LOADING = "AFTER_SHIPMENT_LOADING"
    POST_SHIPMENT_DOCUMENT_PRESENTATION = "POST_SHIPMENT_DOCUMENT_PRESENTATION"


class ReviewRole(str, Enum):
    """Four-eyes control roles. Scrutiny cannot clear; maker cannot self-check.

    SYSTEM is reserved for deterministic machine transitions (not a human review role).
    """

    SCRUTINY = "SCRUTINY"
    MAKER = "MAKER"
    CHECKER = "CHECKER"
    SYSTEM = "SYSTEM"


class CaseWorkflowAction(str, Enum):
    SCRUTINY_COMPLETE = "scrutiny_complete"
    MAKER_RECOMMEND = "maker_recommend"
    MAKER_REQUEST_INFO = "maker_request_info"
    CHECKER_APPROVE = "checker_approve"
    CHECKER_RETURN = "checker_return"
    CHECKER_ESCALATE = "checker_escalate"


class CaseStatus(str, Enum):
    """Three-stage case lifecycle: Scrutiny → Maker → Checker."""

    DRAFT = "DRAFT"
    SCRUTINY_IN_PROGRESS = "SCRUTINY_IN_PROGRESS"
    DOCUMENT_PACK_INCOMPLETE = "DOCUMENT_PACK_INCOMPLETE"
    SCRUTINY_COMPLETE = "SCRUTINY_COMPLETE"
    MAKER_REVIEW = "MAKER_REVIEW"
    INFORMATION_REQUESTED = "INFORMATION_REQUESTED"
    MAKER_RECOMMENDED = "MAKER_RECOMMENDED"
    CHECKER_REVIEW = "CHECKER_REVIEW"
    RETURNED_TO_MAKER = "RETURNED_TO_MAKER"
    CHECKER_APPROVED = "CHECKER_APPROVED"
    ESCALATED = "ESCALATED"
    PROCESSING_FAILED = "PROCESSING_FAILED"


class ReadinessRoute(str, Enum):
    READY_FOR_HUMAN_REVIEW = "READY_FOR_HUMAN_REVIEW"
    DOCUMENT_PACK_INCOMPLETE = "DOCUMENT_PACK_INCOMPLETE"
    EXTRACTION_REVIEW_REQUIRED = "EXTRACTION_REVIEW_REQUIRED"
    MAKER_REVIEW_REQUIRED = "MAKER_REVIEW_REQUIRED"
    CHECKER_REVIEW_REQUIRED = "CHECKER_REVIEW_REQUIRED"
    HIGH_RISK_ESCALATION = "HIGH_RISK_ESCALATION"
    DATA_REVIEW_REQUIRED = "DATA_REVIEW_REQUIRED"


class DocumentType(str, Enum):
    TRADE_FINANCE_APPLICATION = "TRADE_FINANCE_APPLICATION"
    COMMERCIAL_INVOICE = "COMMERCIAL_INVOICE"
    BILL_OF_LADING = "BILL_OF_LADING"
    AIR_WAYBILL = "AIR_WAYBILL"
    PACKING_LIST = "PACKING_LIST"
    CERTIFICATE_OF_ORIGIN = "CERTIFICATE_OF_ORIGIN"
    LETTER_OF_CREDIT = "LETTER_OF_CREDIT"
    BILL_OF_EXCHANGE = "BILL_OF_EXCHANGE"
    INSURANCE_CERTIFICATE = "INSURANCE_CERTIFICATE"
    KYC_KYB_EVIDENCE = "KYC_KYB_EVIDENCE"
    SHIPPING_BILL = "SHIPPING_BILL"
    BILL_OF_ENTRY = "BILL_OF_ENTRY"
    INSPECTION_CERTIFICATE = "INSPECTION_CERTIFICATE"
    OTHER = "OTHER"


class DocumentRequirementState(str, Enum):
    REQUIRED = "REQUIRED"
    CONDITIONALLY_REQUIRED = "CONDITIONALLY_REQUIRED"
    OPTIONAL = "OPTIONAL"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    NOT_PROVIDED = "NOT_PROVIDED"
    POLICY_CONFIGURATION_REQUIRED = "POLICY_CONFIGURATION_REQUIRED"


class CheckStatus(str, Enum):
    PASS = "PASS"
    WARN = "WARN"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    FAIL = "FAIL"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    NOT_AVAILABLE = "NOT_AVAILABLE"
    DATA_UNAVAILABLE = "DATA_UNAVAILABLE"


class AgentName(str, Enum):
    EXTRACTOR = "EXTRACTOR"
    VALIDATOR = "VALIDATOR"
    CHALLENGER = "CHALLENGER"
    ARBITER = "ARBITER"
    CROSS_DOCUMENT_RECONCILER = "CROSS_DOCUMENT_RECONCILER"


class AgentRunStatus(str, Enum):
    COMPLETE = "COMPLETE"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    FAILED = "FAILED"


class ChallengeType(str, Enum):
    SOURCE_AMBIGUITY = "SOURCE_AMBIGUITY"
    CROSS_DOCUMENT_CONFLICT = "CROSS_DOCUMENT_CONFLICT"
    ARITHMETIC_CONFLICT = "ARITHMETIC_CONFLICT"
    MISSING_EVIDENCE = "MISSING_EVIDENCE"


class LEIStatus(str, Enum):
    ISSUED = "ISSUED"
    LAPSED = "LAPSED"
    RETIRED = "RETIRED"
    NOT_FOUND = "NOT_FOUND"
    UNKNOWN = "UNKNOWN"
    DATA_UNAVAILABLE = "DATA_UNAVAILABLE"


class VLEIVerificationStatus(str, Enum):
    VERIFIED_LIVE = "VERIFIED_LIVE"
    VERIFIED_FIXTURE = "VERIFIED_FIXTURE"
    INVALID = "INVALID"
    EXPIRED = "EXPIRED"
    REVOKED = "REVOKED"
    NOT_CONFIGURED = "NOT_CONFIGURED"
    DATA_UNAVAILABLE = "DATA_UNAVAILABLE"


class IdentityResolutionStatus(str, Enum):
    IDENTITY_VERIFIED_BY_LEI = "IDENTITY_VERIFIED_BY_LEI"
    IDENTITY_SUPPORTED_BY_VLEI = "IDENTITY_SUPPORTED_BY_VLEI"
    POTENTIAL_ENTITY_MATCH_REVIEW = "POTENTIAL_ENTITY_MATCH_REVIEW"
    IDENTITY_UNRESOLVED = "IDENTITY_UNRESOLVED"
    IDENTITY_SOURCE_UNAVAILABLE = "IDENTITY_SOURCE_UNAVAILABLE"


class SourceMode(str, Enum):
    OFFICIAL_LIVE = "OFFICIAL_LIVE"
    OFFICIAL_CACHED = "OFFICIAL_CACHED"
    CREDIBLE_AGGREGATOR = "CREDIBLE_AGGREGATOR"
    SYNTHETIC_DEMO = "SYNTHETIC_DEMO"
    NOT_CONFIGURED = "NOT_CONFIGURED"
    DATA_UNAVAILABLE = "DATA_UNAVAILABLE"


class ResultTrigger(str, Enum):
    INITIAL = "INITIAL"
    REPROCESS = "REPROCESS"
    REGWATCH_REPLAY = "REGWATCH_REPLAY"
