/**
 * Mirrored canonical TradePulse enums for frontend consumption.
 * Source of truth: packages/contracts/enums.py
 * Do not invent additional literals here without updating enums.py + tests.
 */

export const TradeProfile = {
  INVOICE_ONLY_PRE_REVIEW: "INVOICE_ONLY_PRE_REVIEW",
  POST_SHIPMENT_DOCUMENT_REVIEW: "POST_SHIPMENT_DOCUMENT_REVIEW",
  LC_DOCUMENT_REVIEW: "LC_DOCUMENT_REVIEW",
  DOCUMENTARY_COLLECTION_REVIEW: "DOCUMENTARY_COLLECTION_REVIEW",
  ENHANCED_TRADE_HOUSE_REVIEW: "ENHANCED_TRADE_HOUSE_REVIEW",
} as const;
export type TradeProfile = (typeof TradeProfile)[keyof typeof TradeProfile];

export const CaseStatus = {
  DRAFT: "DRAFT",
  INGESTED: "INGESTED",
  PROCESSING: "PROCESSING",
  DOCUMENT_PACK_INCOMPLETE: "DOCUMENT_PACK_INCOMPLETE",
  EXTRACTION_REVIEW_REQUIRED: "EXTRACTION_REVIEW_REQUIRED",
  PENDING_MAKER_REVIEW: "PENDING_MAKER_REVIEW",
  MAKER_APPROVED: "MAKER_APPROVED",
  CHECKER_APPROVED: "CHECKER_APPROVED",
  INVESTIGATION_REQUIRED: "INVESTIGATION_REQUIRED",
  CHECKER_REJECTED: "CHECKER_REJECTED",
  PROCESSING_FAILED: "PROCESSING_FAILED",
} as const;
export type CaseStatus = (typeof CaseStatus)[keyof typeof CaseStatus];

export const ReadinessRoute = {
  READY_FOR_HUMAN_REVIEW: "READY_FOR_HUMAN_REVIEW",
  DOCUMENT_PACK_INCOMPLETE: "DOCUMENT_PACK_INCOMPLETE",
  EXTRACTION_REVIEW_REQUIRED: "EXTRACTION_REVIEW_REQUIRED",
  MAKER_REVIEW_REQUIRED: "MAKER_REVIEW_REQUIRED",
  HIGH_RISK_ESCALATION: "HIGH_RISK_ESCALATION",
  DATA_REVIEW_REQUIRED: "DATA_REVIEW_REQUIRED",
} as const;
export type ReadinessRoute = (typeof ReadinessRoute)[keyof typeof ReadinessRoute];

export const DocumentType = {
  COMMERCIAL_INVOICE: "COMMERCIAL_INVOICE",
  BILL_OF_LADING: "BILL_OF_LADING",
  AIR_WAYBILL: "AIR_WAYBILL",
  PACKING_LIST: "PACKING_LIST",
  CERTIFICATE_OF_ORIGIN: "CERTIFICATE_OF_ORIGIN",
  LETTER_OF_CREDIT: "LETTER_OF_CREDIT",
  BILL_OF_EXCHANGE: "BILL_OF_EXCHANGE",
  INSURANCE_CERTIFICATE: "INSURANCE_CERTIFICATE",
  KYC_KYB_EVIDENCE: "KYC_KYB_EVIDENCE",
  SHIPPING_BILL: "SHIPPING_BILL",
  BILL_OF_ENTRY: "BILL_OF_ENTRY",
  INSPECTION_CERTIFICATE: "INSPECTION_CERTIFICATE",
  OTHER: "OTHER",
} as const;
export type DocumentType = (typeof DocumentType)[keyof typeof DocumentType];

export const DocumentRequirementState = {
  REQUIRED: "REQUIRED",
  CONDITIONALLY_REQUIRED: "CONDITIONALLY_REQUIRED",
  OPTIONAL: "OPTIONAL",
  NOT_APPLICABLE: "NOT_APPLICABLE",
  NOT_PROVIDED: "NOT_PROVIDED",
  POLICY_CONFIGURATION_REQUIRED: "POLICY_CONFIGURATION_REQUIRED",
} as const;
export type DocumentRequirementState =
  (typeof DocumentRequirementState)[keyof typeof DocumentRequirementState];

export const CheckStatus = {
  PASS: "PASS",
  WARN: "WARN",
  REVIEW_REQUIRED: "REVIEW_REQUIRED",
  FAIL: "FAIL",
  NOT_APPLICABLE: "NOT_APPLICABLE",
  NOT_AVAILABLE: "NOT_AVAILABLE",
  DATA_UNAVAILABLE: "DATA_UNAVAILABLE",
} as const;
export type CheckStatus = (typeof CheckStatus)[keyof typeof CheckStatus];

export const AgentName = {
  EXTRACTOR: "EXTRACTOR",
  VALIDATOR: "VALIDATOR",
  CHALLENGER: "CHALLENGER",
  ARBITER: "ARBITER",
  CROSS_DOCUMENT_RECONCILER: "CROSS_DOCUMENT_RECONCILER",
} as const;
export type AgentName = (typeof AgentName)[keyof typeof AgentName];

export const VLEIVerificationStatus = {
  VERIFIED_LIVE: "VERIFIED_LIVE",
  VERIFIED_FIXTURE: "VERIFIED_FIXTURE",
  INVALID: "INVALID",
  EXPIRED: "EXPIRED",
  REVOKED: "REVOKED",
  NOT_CONFIGURED: "NOT_CONFIGURED",
  DATA_UNAVAILABLE: "DATA_UNAVAILABLE",
} as const;
export type VLEIVerificationStatus =
  (typeof VLEIVerificationStatus)[keyof typeof VLEIVerificationStatus];

export const IdentityResolutionStatus = {
  IDENTITY_VERIFIED_BY_LEI: "IDENTITY_VERIFIED_BY_LEI",
  IDENTITY_SUPPORTED_BY_VLEI: "IDENTITY_SUPPORTED_BY_VLEI",
  POTENTIAL_ENTITY_MATCH_REVIEW: "POTENTIAL_ENTITY_MATCH_REVIEW",
  IDENTITY_UNRESOLVED: "IDENTITY_UNRESOLVED",
  IDENTITY_SOURCE_UNAVAILABLE: "IDENTITY_SOURCE_UNAVAILABLE",
} as const;
export type IdentityResolutionStatus =
  (typeof IdentityResolutionStatus)[keyof typeof IdentityResolutionStatus];

export const SourceMode = {
  OFFICIAL_LIVE: "OFFICIAL_LIVE",
  OFFICIAL_CACHED: "OFFICIAL_CACHED",
  CREDIBLE_AGGREGATOR: "CREDIBLE_AGGREGATOR",
  SYNTHETIC_DEMO: "SYNTHETIC_DEMO",
  NOT_CONFIGURED: "NOT_CONFIGURED",
  DATA_UNAVAILABLE: "DATA_UNAVAILABLE",
} as const;
export type SourceMode = (typeof SourceMode)[keyof typeof SourceMode];
