#!/usr/bin/env python3
"""Compare every TradePulse enum vocabulary and report drift.

Per docs/adr/001-canonical-contracts-addendum.md section 1.1, the sole canonical
source is packages/contracts/enums.py. This tool reports, for each other
vocabulary in the repo, exactly how it diverges from that canon.

Owner: Atharva (ADR 001 section 1.3 -- contract tests / QA gatekeeper).
Read-only: prints a Markdown report to stdout, never edits source.
"""

from __future__ import annotations

import argparse
import ast
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

CANON = ROOT / "packages" / "contracts" / "enums.py"

# Vocabularies compared against the canon: label -> (path, kind)
VOCABS: list[tuple[str, Path, str]] = [
    ("backend (tradepulse_contracts)", ROOT / "packages" / "contracts" / "tradepulse_contracts" / "enums.py", "py"),
    ("mirrored types.ts", ROOT / "packages" / "contracts" / "types.ts", "ts"),
    ("frontend (lib/mock/types.ts)", ROOT / "apps" / "web" / "lib" / "mock" / "types.ts", "ts"),
]

# Enum classes that the canon defines but that legitimately carry a different
# class name elsewhere. Maps canon name -> alternate names to also consider.
ALIASES: dict[str, tuple[str, ...]] = {
    "CaseStatus": ("CaseState",),
    "TradeProfile": ("TransactionProfile",),
    "VLEIVerificationStatus": ("VleiStatus",),
    "IdentityResolutionStatus": ("IdentityOutcomeLabel",),
}


def parse_python_enums(path: Path) -> dict[str, dict[str, str]]:
    """Return {ClassName: {MEMBER: "wire value"}} for str-enum classes."""
    tree = ast.parse(path.read_text(encoding="utf-8"))
    out: dict[str, dict[str, str]] = {}
    for node in ast.walk(tree):
        if not isinstance(node, ast.ClassDef):
            continue
        members: dict[str, str] = {}
        for stmt in node.body:
            if isinstance(stmt, ast.Assign) and len(stmt.targets) == 1:
                target = stmt.targets[0]
                if isinstance(target, ast.Name) and isinstance(stmt.value, ast.Constant):
                    if isinstance(stmt.value.value, str):
                        members[target.id] = stmt.value.value
        if members:
            out[node.name] = members
    return out


TS_CONST_BLOCK = re.compile(
    r"export const (\w+)\s*=\s*\{(.*?)\}\s*as const;", re.DOTALL
)
TS_CONST_MEMBER = re.compile(r"(\w+)\s*:\s*\"([^\"]+)\"")
TS_UNION_BLOCK = re.compile(
    r"export type (\w+)\s*=\s*((?:\s*\|\s*\"[^\"]+\")+)\s*;", re.DOTALL
)
TS_UNION_MEMBER = re.compile(r"\"([^\"]+)\"")


def parse_ts_enums(path: Path) -> dict[str, dict[str, str]]:
    """Return {TypeName: {MEMBER: "wire value"}} for const objects and string unions."""
    text = path.read_text(encoding="utf-8")
    out: dict[str, dict[str, str]] = {}
    for name, body in TS_CONST_BLOCK.findall(text):
        out[name] = dict(TS_CONST_MEMBER.findall(body))
    for name, body in TS_UNION_BLOCK.findall(text):
        if name in out:
            continue
        out[name] = {v: v for v in TS_UNION_MEMBER.findall(body)}
    return out


def load(path: Path, kind: str) -> dict[str, dict[str, str]]:
    if not path.exists():
        return {}
    return parse_python_enums(path) if kind == "py" else parse_ts_enums(path)


def resolve(vocab: dict[str, dict[str, str]], canon_name: str) -> tuple[str, dict[str, str]] | None:
    """Find the counterpart class for a canon enum, honouring known aliases."""
    if canon_name in vocab:
        return canon_name, vocab[canon_name]
    for alias in ALIASES.get(canon_name, ()):
        if alias in vocab:
            return alias, vocab[alias]
    return None


def compare(canon: dict[str, str], other: dict[str, str]) -> dict[str, list[str]]:
    """Classify drift between two {MEMBER: value} maps."""
    missing = sorted(set(canon) - set(other))
    extra = sorted(set(other) - set(canon))
    value_drift = sorted(
        f"{m}: canon `{canon[m]}` vs `{other[m]}`"
        for m in set(canon) & set(other)
        if canon[m] != other[m]
    )
    return {"missing": missing, "extra": extra, "value_drift": value_drift}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--strict",
        action="store_true",
        help="exit 1 when any drift is found (for CI once the canon is adopted)",
    )
    args = parser.parse_args()

    # Windows consoles default to cp1252; force UTF-8 so the report round-trips.
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")

    canon = parse_python_enums(CANON)
    lines: list[str] = []
    total_drift = 0

    lines.append("# Contract Reconciliation Report")
    lines.append("")
    lines.append(
        "Generated by `scripts/contract_diff.py`. Do not hand-edit — regenerate instead."
    )
    lines.append("")
    lines.append(
        f"Canonical source (ADR 001 s1.1): `{CANON.relative_to(ROOT).as_posix()}` "
        f"— {len(canon)} enum(s)."
    )
    lines.append("")

    for label, path, kind in VOCABS:
        vocab = load(path, kind)
        rel = path.relative_to(ROOT).as_posix()
        lines.append(f"## {label}")
        lines.append("")
        lines.append(f"`{rel}` — {len(vocab)} type(s) parsed.")
        lines.append("")

        rows: list[str] = []
        for canon_name, canon_members in sorted(canon.items()):
            found = resolve(vocab, canon_name)
            if found is None:
                rows.append(f"| `{canon_name}` | — | **absent** | not defined in this vocabulary |")
                total_drift += 1
                continue
            other_name, other_members = found
            drift = compare(canon_members, other_members)
            notes: list[str] = []
            if other_name != canon_name:
                notes.append(f"renamed to `{other_name}`")
            if drift["missing"]:
                notes.append("missing: " + ", ".join(f"`{m}`" for m in drift["missing"]))
            if drift["extra"]:
                notes.append("extra: " + ", ".join(f"`{m}`" for m in drift["extra"]))
            if drift["value_drift"]:
                notes.append("wire-value drift: " + "; ".join(drift["value_drift"]))
            if not notes:
                rows.append(f"| `{canon_name}` | `{other_name}` | ok | — |")
                continue
            total_drift += 1
            rows.append(
                f"| `{canon_name}` | `{other_name}` | **drift** | " + "<br>".join(notes) + " |"
            )

        lines.append("| Canonical enum | Counterpart | State | Detail |")
        lines.append("|---|---|---|---|")
        lines.extend(rows)
        lines.append("")

    lines.append("## Summary")
    lines.append("")
    lines.append(f"Canonical enums: **{len(canon)}**")
    lines.append("")
    lines.append(f"Enum comparisons showing drift: **{total_drift}**")
    lines.append("")

    print("\n".join(lines))

    if args.strict and total_drift:
        print(f"\nDrift detected in {total_drift} comparison(s).", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
